# These are supported funding model platforms

patreon: metroui
open_collective: metro4
<a href="https://www.buymeacoffee.com/pimenov">
	<img src="https://metroui.org.ua/images/buy-me-coffee2.png" height="38">
</a>
